MCU = atmega32u4
F_CPU = 16000000
ARCH = AVR8
F_USB = 16000000

OPT_DEFS += -DINTERRUPT_CONTROL_ENDPOINT
OPT_DEFS += -DBOOTLOADER_SIZE=4096


NO_USB_STARTUP_CHECK = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes

BOOTLOADER = atmel-dfu
BOOTMAGIC_ENABLE = lite       # Virtual DIP switch configuration(+1000)

NKRO_ENABLE = yes


CUSTOM_MATRIX = lite

MIDI_ENABLE = no
AUDIO_ENABLE = no
BLUETOOTH_ENABLE = no
SRC += matrix.c